/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE "Department_id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "Department_id_seq" IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: "Answers" ************************/

/* Build Table Structure */
CREATE TABLE "Answers"
(
	id INTEGER NOT NULL,
	question_id INTEGER NULL,
	classroom_id INTEGER NULL,
	response BIGINT NOT NULL
);

/* Add Primary Key */
ALTER TABLE "Answers" ADD CONSTRAINT "pkAnswers"
	PRIMARY KEY (id);


/******************** Add Table: "Classroom" ************************/

/* Build Table Structure */
CREATE TABLE "Classroom"
(
	id INTEGER NOT NULL,
	instructor_id INTEGER NULL,
	academic_year INTEGER NOT NULL,
	semester BIGINT NOT NULL,
	course_id CHAR(100) NULL
);

/* Add Primary Key */
ALTER TABLE "Classroom" ADD CONSTRAINT "pkClassroom"
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON TABLE "Classroom" IS 'Student course table';


/******************** Add Table: "Course" ************************/

/* Build Table Structure */
CREATE TABLE "Course"
(
	id CHAR(100) NOT NULL,
	course_code VARCHAR(100) NOT NULL,
	credit_hr INTEGER NULL,
	ects INTEGER NOT NULL,
	dept_id INTEGER NULL
);

/* Add Primary Key */
ALTER TABLE "Course" ADD CONSTRAINT "pkCourse"
	PRIMARY KEY (id);


/******************** Add Table: "Department" ************************/

/* Build Table Structure */
CREATE TABLE "Department"
(
	id SMALLINT DEFAULT nextval('"schemaA"."Department_id_seq"'::regclass) NOT NULL,
	dept_name VARCHAR(100) NOT NULL,
	dept_head VARCHAR(100) NOT NULL,
	dept_type ENUM('School','Center') NULL
);

/* Add Primary Key */
ALTER TABLE "Department" ADD CONSTRAINT "pkDepartment"
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON COLUMN "Department".dept_name IS 'Department Number';


/******************** Add Table: "Instructor" ************************/

/* Build Table Structure */
CREATE TABLE "Instructor"
(
	id INTEGER NOT NULL,
	instructor_name VARCHAR(100) NOT NULL,
	dept_id INTEGER NULL,
	title VARCHAR(100) NOT NULL
);

/* Add Primary Key */
ALTER TABLE "Instructor" ADD CONSTRAINT "pkInstructor"
	PRIMARY KEY (id);


/******************** Add Table: "Program" ************************/

/* Build Table Structure */
CREATE TABLE "Program"
(
	id INTEGER NOT NULL,
	dept_id SMALLINT NOT NULL,
	name VARCHAR(200) NOT NULL,
	stream VARCHAR(200) NOT NULL,
	program_type ENUM('regular','extension,'summer'') NOT NULL,
	degree_program ENUM('Undergraduate','Graduate','PhD','Certificate') NOT NULL
);

/* Add Primary Key */
ALTER TABLE "Program" ADD CONSTRAINT "pkProgram"
	PRIMARY KEY (id);


/******************** Add Table: "Question" ************************/

/* Build Table Structure */
CREATE TABLE "Question"
(
	id INTEGER NOT NULL,
	question VARCHAR(100) NOT NULL
);

/* Add Primary Key */
ALTER TABLE "Question" ADD CONSTRAINT "pkQuestion"
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON TABLE "Question" IS 'questions ...';


/******************** Add Table: "Registration" ************************/

/* Build Table Structure */
CREATE TABLE "Registration"
(
	id INTEGER NOT NULL,
	student_id INTEGER NOT NULL,
	classroom_id INTEGER NOT NULL,
	has_rated ENUM('Rated','Unrated') NOT NULL
);

/* Add Primary Key */
ALTER TABLE "Registration" ADD CONSTRAINT "pkRegistration"
	PRIMARY KEY (id);


/******************** Add Table: "Student" ************************/

/* Build Table Structure */
CREATE TABLE "Student"
(
	id INTEGER NOT NULL,
	u_id INTEGER NOT NULL,
	year INTEGER NOT NULL,
	program_id INTEGER NOT NULL,
	student_id VARCHAR(20) NOT NULL
);

/* Add Primary Key */
ALTER TABLE "Student" ADD CONSTRAINT "pkStudent"
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON COLUMN "Student".year IS 'year';


/******************** Add Table: "User" ************************/

/* Build Table Structure */
CREATE TABLE "User"
(
	id INTEGER NOT NULL,
	reg_date DATE NOT NULL,
	user_name VARCHAR(100) NOT NULL,
	user_type ENUM('student','admin') NOT NULL,
	password VARCHAR(100) NOT NULL
);

/* Add Primary Key */
ALTER TABLE "User" ADD CONSTRAINT "pkUser"
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON TABLE "User" IS 'The user ...';